services:
  shoppinglist_backend:
    image: ${DOCKER_REGISTRY-}shoppinglistbackend
    container_name: Api
    build:
      context: .
      dockerfile: shoppingList_backend/Dockerfile

    env_file:
       - ./.env

    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${HTTPS_CERT_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERT_PASS}
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
        - ${API_OUT_HTTPS}:${API_IN_HTTPS}
        - ${API_OUT_HTTP}:${API_IN_HTTP}
    networks:
      - Database
    depends_on:
      GroceryListDB:
        condition: service_healthy
    volumes:
      - ./https:/https

  GroceryListDB:
    image: postgres:14-alpine
    platform: linux/amd64
    container_name: GroceryListDB
    env_file:
        - ./.env
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
    volumes:
        - ./.containers/PetersPizza/Database:/var/lib/postgresql/data
    expose:
        - ${DATABASE_IN}
    ports:
      - ${DATABASE_OUT}:${DATABASE_IN}
    networks:
        - Database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  Database:
